test_lidar_publisher:
  ros__parameters:
    # 发布的话题名
    topic: "/perception/lidar_cluster"
    # 发布频率（Hz）
    publish_rate: 10.0
    # 测试模式： "identity" 发布原始地图； "shifted" 发布旋转+平移后的地图
    mode: "identity"
    pcd_path: "/home/limdegcai/GSMART/CODE/skidpad_ws/src/skidpad_icp/config/skidpad.pcd"
    # 若 mode=shifted，可指定如下变换（齐次坐标系，旋转和平移）
    start_length: 15.0
    lidar2imu: 1.87
    transform:
      roll: 0.0   # 绕 x 轴旋转（弧度）
      pitch: 0.0
      yaw: 0.0175    # 1度
      translation_x: 0.1
      translation_y: -0.05
      translation_z: 0.0